### ISSUE TITLE
Django 2.0 Release?

### ISSUE THREAD

**Issue by ambsw-technology** [saxix/django-concurrency#152]
We're trying to complete a massive dependency upgrade.  I see that support is buried in the dev branch.  Is there an ETA for a release?  Are there specific issues that need resolved to push it across the finish line?

**Comment by ambsw-technology** [comment]
Sorry.  I got confused and changed `MIDDLEWARE_CLASSES` to `MIDDLEWARE` which caused the issue.

**Comment by ambsw-technology** [comment]
OK.  After I cleaned up all my other issues, I still needed to use the development branch to address odd behaviors on Django 2.1.  Is there anything in particular needing resolved before you can cut another pip release?

**Comment by saxix** [comment]
branch [2.0](https://github.com/saxix/django-concurrency/tree/release/2.0) ready, will try to release tomorrow.
