### ISSUE TITLE
NameError: name 'RecordModifiedError' is not defined

### ISSUE THREAD

**Issue by smelehy** [saxix/django-concurrency#170]
I am probably missing something simple, but I don't understand python exceptions well enough.  I installed django-concurrency using pip, updated the settings.MIDDLEWARE with   'concurrency.middleware.ConcurrencyMiddleware',.

 I looked through the docs, but I can't find how the 'RecordModifiedError' exceptions gets defined.  Can you give me anything to check?  I am trapping the exception like any other exception.

` try:
        queryset.save()
except RecordModifiedError as err:
`

`MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'concurrency.middleware.ConcurrencyMiddleware',
]`

**Comment by saxix** [comment]
You do need the middleware if you don't want to implement some very complex logic.
`RecordModifiedError` is defined in https://github.com/saxix/django-concurrency/blob/815230336aa173bd73df1f411a77434944958c39/src/concurrency/exceptions.py#L10 and raised in https://github.com/saxix/django-concurrency/blob/815230336aa173bd73df1f411a77434944958c39/src/concurrency/views.py#L14.

You can customize what should happen in case of conflicts overriding `CONCURRENCY_ CALLBACK ` or `CONCURRENCY_HANDLER409`

The first one is the low-level callback the other is the view where the middleware redirect the browser in case os conflicts.

Hope this clarifies a bit, let me know in case.

**Comment by smelehy** [comment]
That clarifies greatly.  I got it working now.  Thanks for the help.
