### ISSUE TITLE
form.is_valid() causes concurrency.exceptions.VersionError

### ISSUE THREAD

**Issue by smelehy** [saxix/django-concurrency#176]
The form.is_valid() is True, but the form.is_valid() method results in an exceptions.  The other strange thing is the that version number of the form.data['version'] is equal to the record in the data base - in other words, the record hasn't changed.

**Comment by smelehy** [comment]
...also, saving the record with object.save() is successful - no concurrency exception error.  The error is only thrown on the form.is_valid()

**Comment by saxix** [comment]
sorry for the very late reply to this ticket. I need more details to get what is happening.

Not  sure to understand this sentence "The form.is_valid() is True, but the form.is_valid() method results in an exceptions"

Is it possible that the validation error does not come from concurrency? 
`form.data['version']` should be equal to the version on the db if no other updates happening.

Can you share some more details? What is the flow?
