### ISSUE TITLE
CBV UpadteView raise RecordModifiedError on form.save() without modif

### ISSUE THREAD

**Issue by euchi** [saxix/django-concurrency#190]
Even without update of the model the RecordModifiedError  is raised.
I use your get_diff, conflict example and there is no diff displayed in 409.html.
The expception is raised on form.save() in my code below :
``` python
def form_valid(self, form):
        context = self.get_context_data()
        ...
        with transaction.atomic():
            self.object = form.save()
```

**Comment by saxix** [comment]
did u have version field in your form ?

**Comment by saxix** [comment]
closed due to inactivity
