### ISSUE TITLE
Documentation/Variable name is super unclear

### ISSUE THREAD

**Issue by boatcoder** [saxix/django-concurrency#206]
> MANUAL_TRIGGERS
> Default: False
> 
> If false do not automatically create triggers, you can create them using triggers management command
> management command or manually using your DB client.

MANUAL_TRIGGERS = False means to not *automatically* create triggers?

Wouldn't a better name be AUTOMATIC_TRIGGERS?  Could you clarify why it is called MANUAL_TRIGGERS

**Comment by saxix** [comment]
Whoops. The doc is wrong. the idea was  "MANUAL_TRIGGERS=True" == "I want to manually create my triggers" 

It is better to rename it  as "AUTO_CREATE_TRIGGERS" in future releases.

**Comment by boatcoder** [comment]
Thanks guys!
