### ISSUE TITLE
Unexpected raise using update_fields

### ISSUE THREAD

**Issue by MaurizioPilia** [saxix/django-concurrency#213]
Hi,

I need to update a field without increase the instance version so i tried the code in the doc:
```
x1 = MyModel.objects.create(name='abc')
x2 = MyModel.objects.get(pk=x1.pk)

x1.save(update_fields=['username'])  # skip update version number
x2.save()  # saved
```
but it doesn't work as documentation says, the last line raise me an unexpected exception RecordModifiedError

**Comment by saxix** [comment]
`update_fields` cannot be used to by-pass concurrency check (this is a intended beahviour) , you can use [disable_concurrency](https://django-concurrency.readthedocs.io/en/latest/api.html#disable-concurrency)  or [concurrency_disable_increment](https://django-concurrency.readthedocs.io/en/latest/api.html#concurrency-disable-increment) depending on what you need.

**Comment by MaurizioPilia** [comment]
Ok, i probably misunderstood the doc.
Thanks,
