### ISSUE TITLE
Django 4.0 is released

### ISSUE THREAD

**Issue by raratiru** [saxix/django-concurrency#232]
Version 2.3 of concurrency is not compatible with Django-4.0, for example:

https://github.com/saxix/django-concurrency/blob/88e3a205e905c228db366e591b3db9729c0a60ed/src/concurrency/fields.py#L13

https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0

When will the develop branch be released?

**Comment by domdinicola** [comment]
working on it, tests are failing

**Comment by raratiru** [comment]
I just noticed the [dj4 branch](https://github.com/saxix/django-concurrency/tree/dj4), this seems like a nasty error.

https://github.com/saxix/django-concurrency/blob/60e81ebcc638760acc976349b020494cb954e37b/src/concurrency/fields.py#L268-L272

```
File "/home/runner/work/django-concurrency/django-concurrency/src/concurrency/fields.py", line 270, in _wrap_model_methods
    super()._wrap_model_methods(model)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by domdinicola** [comment]
trying to fix tests https://github.com/saxix/django-concurrency/pull/234
looks ManagementForm stays cached among tests
