### ISSUE TITLE
Getting a model in a view: is there a way to know if someone else is using it?

### ISSUE THREAD

**Issue by esseti** [saxix/django-concurrency#245]
We have - somohow - a blog app . where there's the possibility to edit a blog post.
Now, the blog post editing can require some time.
Thus, user A arrives, open the editor of the post and start writing, then saves it. 
This works as long as no-one-else arrives in the meanwhile and does the editing.

now, can I rely on this package to prevent problems? as far as I understood:
- A start editing the post
- the B arrives, and start editing the post
- A saves it ->saved
- B saves it -> gets an error -> time wasted since the diff are huge

Is there a way, a field, something that can be check and that we can use to tell to B, when arrives and wants to edit we can block him?
is there a way to know the "lock"?

btw, what happens if A does not save and quits? will B still get error?

**Comment by saxix** [comment]
concurrency implements optimistic-lock there is no "real" lock. You could add a "LastModifiedUser" field to inform the user who did last change.
