### ISSUE TITLE
Django-5.0: AttributeError

### ISSUE THREAD

**Issue by raratiru** [saxix/django-concurrency#249]
https://github.com/saxix/django-concurrency/blob/0ce2f02b23d987cef035b1bbbac6e881d56adb0f/src/concurrency/admin.py#L38-L39

From the [docs](https://docs.djangoproject.com/en/dev/releases/5.0/):

> The undocumented django.contrib.admin.helpers.checkbox is removed.

The error:

`AttributeError: module 'django.contrib.admin.helpers' has no attribute 'checkbox'`

**Comment by saxix** [comment]
fixed in dev -
