### ISSUE TITLE
your example is off

### ISSUE THREAD

**Issue by sjatkins2** [saxix/django-concurrency#48]
You get the same model instance twice and save each and you get a concurrency error?  Why exactly?  You haven't changed any fields!  Optimistic concurrency means detecting changes to an object at save/commit that overwrite concurrent changes.  It generally requires keeping track of mutations of the object somehow or using a shadow object.  If this really works like the example it is broken by design.

**Comment by saxix** [comment]
dc is architectural component not functional, avoid saving if no data have been changed is on charge of the application logic (if needed).  There is too much overhead to put the logic you mention in a so abstract component. From the functional point of view is possible that only a timestamp field need to be changed and you need a concurrency check too, so the record is changed even if you do not change any value. it is only an example.
