### ISSUE TITLE
update_fields

### ISSUE THREAD

**Issue by oppianmatt** [saxix/django-concurrency#49]
How does the use of update_fields on model save work? Does it just work? Is there any caveats? 

Nothing obvious in the docs.

**Comment by saxix** [comment]
just added some infos.

related commit [here](6c1048cf5cadb07cb083e02c47b1fb8d9ed1c853), [faq](http://django-concurrency.readthedocs.org/en/develop/faq.html#how-is-managed-update-fields) and related [tests](https://github.com/saxix/django-concurrency/blob/6c1048cf5cadb07cb083e02c47b1fb8d9ed1c853/tests/test_base.py#L74)
