### ISSUE TITLE
Add support Django 1.8

### ISSUE THREAD

**Issue by liminspace** [saxix/django-concurrency#50]
Need update to support Django1.8:
concurrency\forms.py:7: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
from django.utils.importlib import import_module

concurrency\utils.py:7: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
from django.db.models.loading import get_models, get_apps

**Comment by saxix** [comment]
fixed in 0.9
