### ISSUE TITLE
loaddata management command fails with RecordModifiedError

### ISSUE THREAD

**Issue by JoeGermuska** [saxix/django-concurrency#52]
We tried to use `dumpdata` and `loaddata` to set up a realistic baseline developer database, and got errors because `dumpdata` carries the versions with it.

It would be nice to have a workaround for this. If you're interested, we could look into a pull request, but we'd want to make sure it fits with your overall vision.

I see some related issues like #13 so if you feel this is a closed question from `django-concurrency`'s perspective, just say so.

**Comment by JoeGermuska** [comment]
ugh, the core `loaddata` and `dumpdata` commands aren't very well factored to slip this in. Well, still interested in your opinion about whether this is even something for concurrency to address.

**Comment by saxix** [comment]
you can try to use this in your `loaddata`

```
from concurrency.config import conf
conf.ENABLED = False
```

**Comment by jmp0xf** [comment]
Hi @JoeGermuska, did the solution provided by @saxix work?

**Comment by saxix** [comment]
woops, `conf.ENABLED` is only available in `develop` branch

**Comment by Sovetnikov** [comment]
This code works fine to prevent RecordModifiedError with loading fixtures in Django TestCase:
```
@classmethod
    def setUpClass(cls):
        from concurrency.config import conf
        conf.ENABLED = False
        super(ObjectSpecTest, cls).setUpClass()
        conf.ENABLED = True
```

**Comment by YAmikep** [comment]
@saxix I see that this issue is closed.
Is there a plan to make this work out of the box without additional code like above?
