### ISSUE TITLE
Documentation about django-reversion compatibility is probably outdated.

### ISSUE THREAD

**Issue by ticosax** [saxix/django-concurrency#53]
Because the method `render_revision_form` does not exist in latest release.

https://django-concurrency.readthedocs.org/en/latest/cookbook.html#recover-deleted-record-with-django-reversion

Sorry, I didn't have time to investigate further, but I open the issue now in case someone have a quick answer. In any case, I will come back later with some suggestions.

**Comment by blueyed** [comment]
It was removed / changed in https://github.com/etianen/django-reversion/commit/c4838999da70e233f9c4e85d03d798b6aa8c9509.

**Comment by ticosax** [comment]
@blueyed thank you for the help.

**Comment by saxix** [comment]
thanks, will be fixed in the next release

**Comment by saxix** [comment]
solved on develop
