### ISSUE TITLE
Incorrect default for IntegerVersionField

### ISSUE THREAD

**Issue by vmspike** [saxix/django-concurrency#54]
All VersionField's has default = 0
For IntegerVersionField it's incorrect and cause the following issue:
Concurrency silently doesn't work for first time object editing after django-concurrency implementation.
When I load one object (with IntegerVersionField value = 0) in two tabs and save 1st, then 2nd, 1st editing will be silently oveddided.

**Comment by saxix** [comment]
django version ? this is strange as should not exists version==0 on the db.
the `pre_save` handler always change the default and `test_standard_save` check this behaviour

**Comment by vmspike** [comment]
Django 1.8, django-concurrency 0.9.
I've added IntegerVersionField to my custom model. Model already has data, so "version" field (actually name "rev") added by new automatically created migration. Exactly after migration all values of "rev" field is 0. After first specific instance save its "rev" value became correct.
To fix this I had to use the following workaround:
```python
for o in chain(Model1.objects.all(), Model2.objects.all(), ModelN.objects.all()):
    o.save(update_fields=['rev'])
```

**Comment by saxix** [comment]
yep it's a bug, anyway is not in the default value but in the missing `deconstruct()` method that should se to `1` the initial value (as in south). I fixed it locally, plan to release soon. Thanks for the notice

**Comment by saxix** [comment]
solved on develop

**Comment by pathway** [comment]
Why is this issue closed in 2015, today I have the same issue: AutoIncVersionField defaults to 0, doesn't work correctly until it gets to 1.
Can we please open this bug again @saxix ?

**Comment by saxix** [comment]
I have reopened this issue, anyway it is not clear how it is possible to have '0'  as value in a saved record without manually update it. @pathway can you provide some info about your use case. Otherwise I close this issue as "missing documentation".

**Comment by claytondaley** [comment]
We ran into an issue (with Django Rest Framework) where the (DRF) serializer was defaulting to zero.  That was getting passed through to Django Concurrency and creating issues.  Can you confirm that the code that's creating the object isn't setting defaults?

**Comment by pathway** [comment]
All I did, was add `concurrency_version = AutoIncVersionField()` to existing models, and run migrate.
New field was added with starting value 0.  Nothing to do with DRF or object creation.

Did I do something wrong?   Am I supposed to set `concurrency_version = AutoIncVersionField(default=1)` or something similar?

I understand its a doc issue, thats fine.

**Comment by saxix** [comment]
@pathway Ok I have found the error: whe you add a FersionField later, even if the migation is created with `default=1`, records are saved with value `0`, I'll open a new ticked for that in your case  set `CONCURRENCY_IGNORE_DEFAULT=False` should prevent the error, kindly let me know otherwise.

**Comment by pathway** [comment]
@saxix with `default=1` and `CONCURRENCY_IGNORE_DEFAULT=False`, initial field remains 0, but conflicts are corrected even on first try. So yes this corrects the error for now, thank you!
