### ISSUE TITLE
does django-concurrency support front end update?

### ISSUE THREAD

**Issue by andy2046** [saxix/django-concurrency#69]
Hi,

I configured django-concurrency for my app, and it works for the model in admin site, but from my own custom detail template html page which calls view function to update/save model, it does not work, how to configure to support this? thanks.

**Comment by saxix** [comment]
what error do you have? have you added version field to your form ? have a look at https://github.com/saxix/django-concurrency/blob/develop/tests/test_forms.py how to use forms with concurrency

**Comment by andy2046** [comment]
I am using ajax to post data to view then save the post to model, my code attached below, in this case, how can I implement concurrency in my app? I tried concurrency_check but does not work, in your code, the value field is my current version value so entry always return current record so no conflict detected, pls advise, thanks.

value = version_value or getattr(model_instance, version_field.name)
is_versioned = value != version_field.get_default()
kwargs = {'pk': model_instance.pk, version_field.name: value}
entry = model_instance.__class__._base_manager.filter(**kwargs)
if not entry:
            logger.debug("Conflict detected"

models.py
class mymodel(models.Model):
    myid = models.CharField(max_length = 50,primary_key=True)
    data = models.CharField(max_length = 50)
    version = IntegerVersionField()
    def save(self, *args, **kwargs):
        concurrency_check(self, *args, **kwargs)
        super(mymodel, self).save(*args, **kwargs) # Call the "real" save() method
views.py

def myview(request)
    data= request.POST['data']
    myinstance,created = mymodel.objects.get_or_create(myid= id)
    myinstance.data=data
    myinstance.save() 

settings.py
CONCURRENCY_ENABLED=True

admin.py
class mymodelAdmin(ConcurrentModelAdmin, admin.ModelAdmin):
    ...

**Comment by saxix** [comment]
you don't need to call `concurrency_check` it's automatically called as you added `VersionField` to your model. Seems you do are not passing back the version you have fetched.

What version of DC are you using ?

have a look [here](https://github.com/saxix/django-concurrency/issues/36) and [here](https://django-concurrency.readthedocs.io/en/latest/settings.html#ignore-default)

**Comment by andy2046** [comment]
I am using django-concurrency 1.3.1, my model has versionfield, as shown below, and by default 'IGNORE_DEFAULT' is True, how this default check works? If it's first save it works, but if the record is already existed, 2 users load the record concurrently, one user updated the record, then the other user's update will overwrite the update, how to prevent this? thanks. 

models.py
class mymodel(models.Model):
myid = models.CharField(max_length = 50,primary_key=True)
data = models.CharField(max_length = 50)
version = IntegerVersionField()

 defaults = {
        'ENABLED': True,
        'MANUAL_TRIGGERS': False,
        'FIELD_SIGNER': 'concurrency.forms.VersionFieldSigner',
        'POLICY': CONCURRENCY_LIST_EDITABLE_POLICY_SILENT,
        'CALLBACK': 'concurrency.views.callback',
        'HANDLER409': 'concurrency.views.conflict',
        'IGNORE_DEFAULT': True,
    }

**Comment by andy2046** [comment]
when I set 'IGNORE_DEFAULT' to False, this only works for default value conflict, but for existing record, if it's REST API update, by default it does not prevent from concurrent update, and I have to add hidden field in my REST UI to store current version and do the checking when save the record.

any other workable solution without much code change? thanks.

**Comment by andy2046** [comment]
@claytondaley may I also seek your advice on this? thanks.

**Comment by claytondaley** [comment]
> I have to add hidden field in my REST UI to store current version...

This is how optimistic locking (OL) works.  Every update must include the version number that it is working on.  That's how an OL framework detects the concurrency issue.

> ... and do the checking when save the record.

django-concurrency (and other OL libraries) do this checking so you shouldn't need to.

Does that clear up your confusion?

**Comment by claytondaley** [comment]
FYI... IGNORE_DEFAULT is a backwards compatibility mode.  It really should be False for new users.

**Comment by andy2046** [comment]
@claytondaley thanks a lot for the advice, but i do not quite understand the recommendation below, could you help to give a example, thx

django-concurrency (and other OL libraries) do this checking so you shouldn't need to (i.e. +1 to saxix's recommendation to remove your concurrency_check function).

could you help to advise how to remove the concurrency_check func without passing the version number to save model

**Comment by claytondaley** [comment]
The currency check is automatically called when you save a model with an `IntegerVersionField`.  Here's a nice compact example that should work:

```
def myview(request):
    post = request.POST
    myinstance,created = mymodel.objects.get_or_create(myid=post['id'])
    myinstance.data = post['data']
    myinstance.version = post['version']
    myinstance.save()
```

**Comment by andy2046** [comment]
django-concurrency (and other OL libraries) do this checking so you shouldn't need to (i.e. +1 to saxix's recommendation to remove your concurrency_check function).

**Comment by andy2046** [comment]
@claytondaley thanks a lot for the advice
