### ISSUE TITLE
get next version return null when IGNORE_DEFAULT set to False

### ISSUE THREAD

**Issue by andy2046** [saxix/django-concurrency#70]
Hi,
get next version return null when IGNORE_DEFAULT set to False, old_value is null, by right it should be 0

  File "...\Anaconda2\lib\site-packages\concurrency\fields.py", line 182, in _do_update
    new_version = field._get_next_version(model_instance)
  File "...\Anaconda2\lib\site-packages\concurrency\fields.py", line 235, in _get_next_version
    return max(int(old_value) + 1, (int(time.time() * 1000000) - OFFSET))
ValueError: invalid literal for int() with base 10: ''

**Comment by claytondaley** [comment]
It looks like the problem is `int(old_value)`.  Can you add a `pprint()` to your view to see exactly what value is in the POST?

**Comment by andy2046** [comment]
Hi @claytondaley the version value in UI is null for new record as there is no record in model, then in view the value is u'', but getattr should return default value 0, unfortunately it does not, if I hardcode old_value = old_value if bool(old_value) else 0 the default value will be zero but another issue raise, which is:

  File "...\Anaconda2\lib\site-packages\django\db\models\base.py", line 827, in _save_table
    forced_update)
  File "...\Anaconda2\lib\site-packages\concurrency\fields.py", line 208, in _do_update
    version_field._set_version_value(model_instance, old_version)
  File "...\Anaconda2\lib\site-packages\concurrency\fields.py", line 148, in _set_version_value
    setattr(model_instance, self.attname, int(value))
ValueError: invalid literal for int() with base 10: ''

<input class="myclass" id="version" value="" type="hidden"> 

old_value = getattr(model_instance, self.attname, 0)

**Comment by andy2046** [comment]
maybe the best solution is to set default value 0 for new record in UI, which is

`<input class="myclass" id="version" value="0" type="hidden" />`

**Comment by andy2046** [comment]
@claytondaley can I set initial value for VersionField to 0 to solve the issue? thanks.

**Comment by claytondaley** [comment]
Vesionfield already defaults to zero, but you're overriding the value in the POST so your UI should also default to zero.  In fact, your UI defaults should probably match your Model defaults generally speaking.

**Comment by andy2046** [comment]
@claytondaley noted, so is it possible to keep the version field default value if I do not set default value on UI? thanks

**Comment by claytondaley** [comment]
Only the way you've already mentioned... a check in the view like `instance.version = POST['version'] if POST['version'] is not None else 0`.  There's no way for the model to "know better".

**Comment by andy2046** [comment]
@claytondaley thanks for the advice
