### ISSUE TITLE
South migration not working

### ISSUE THREAD

**Issue by djsan15** [saxix/django-concurrency#73]
I am trying to integrate django-concurrency into my django project (v 1.6), but whenever I run schemamigration for south it gives the following error:
````
 ! Cannot freeze field 'shop.variation.version'
 ! (this field has class concurrency.fields.IntegerVersionField)

 ! South cannot introspect some fields; this is probably because they are custom
 ! fields. If they worked in 0.6 or below, this is because we have removed the
 ! models parser (it often broke things).
 ! To fix this, read http://south.aeracode.org/wiki/MyFieldsDontWork
````

**Comment by saxix** [comment]
south support has been removed a while ago. You can use a old version (<1.0) or try to add these lines to your code

```
from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^concurrency\.fields\.IntegerVersionField"])
```

see [South Custom Fields](http://south.readthedocs.io/en/latest/customfields.html) for further info

**Comment by djsan15** [comment]
Okay thanks. I think you should add this to your documentation. Its not mentioned clearly anywhere. Thanks anyways. :)
