### ISSUE TITLE
Is the package dead?

### ISSUE THREAD

**Issue by liminspace** [saxix/django-concurrency#77]
Or not? I want use it with django 1.11.

**Comment by saxix** [comment]
the project is alive. it is tested with 1.10 as per https://travis-ci.org/saxix/django-concurrency/ and should work with 1.11 too

**Comment by liminspace** [comment]
When will be released new version in pypi? It's not good idea to use git-repository-version in a project.

**Comment by saxix** [comment]
v1.4 just released
