### ISSUE TITLE
triggers not created during tests

### ISSUE THREAD

**Issue by YAmikep** [saxix/django-concurrency#78]
Hi,

Is there anything special to do to get the triggers to be created when running the tests?

When I run the tests on my project, I get this
```
WARNINGS:
?: (concurrency.W001) Missed trigger for field beyond.User.version
```

When I check the test database, the triggers are never created.

I am using django 1.11 and I have tried with the latest commit: https://github.com/saxix/django-concurrency/commit/2c92198f845dc2f3279eaa855978b155e36e422d

Thanks

**Comment by saxix** [comment]
triggers should be automatically created (if MANUAL_TRIGGERS=False) using a post_migrate signal, try to call `create_triggers` manually in your test setup.

**Comment by saxix** [comment]
any news about this issue ?

**Comment by saxix** [comment]
@YAmikep can you try branch https://github.com/saxix/django-concurrency/tree/feature/issue_80 to see if it solves this issue ?

**Comment by saxix** [comment]
any feedback on this issues? is v1.4 still affected ?

**Comment by YAmikep** [comment]
Sorry for the delay. Yes, same issue after updating to 1.4
If nobody has the issue, I guess it must be my test settings so we can close the issue.
