### ISSUE TITLE
documentation: admin fields/fieldsets override

### ISSUE THREAD

**Issue by agfunder** [saxix/django-concurrency#81]
If you use ConcurrentModelAdmin , and you manually set fieldsets or fields in admin, you must ensure the version field gets added to the admin.  Otherwise concurrency checks will not be enforced.

This small detail took me almost 2 hours to discover.  1 line of documentation would protect future users from this.

Btw: thank you for a very cool library :+1:

**Comment by saxix** [comment]
a4e54601dc07a418a6b2ac89565c56078e72b2cb adds a warning in documentation and a check for the [System check framework](https://docs.djangoproject.com/en/1.11/ref/checks/) (only enabled  for django >= 1.11)
