### ISSUE TITLE
'compilemessages' breaks with ValueError

### ISSUE THREAD

**Issue by pirm-in** [saxix/django-concurrency#84]
After installing django-concurrency, running `manage.py compilemessages` raises a `ValueError: plural forms expression could be dangerous` because of a bad Plural-Forms header in the https://github.com/saxix/django-concurrency/blob/develop/src/concurrency/locale/en/LC_MESSAGES/django.po#L18. 

django-mptt had the same issue https://github.com/django-mptt/django-mptt/issues/156

I have created a pull request for this https://github.com/saxix/django-concurrency/pull/83

Thank you!

**Comment by saxix** [comment]
#83 merged, thanks for the PR
