### ISSUE TITLE
Supports python 2.7?

### ISSUE THREAD

**Issue by kevinmickey** [saxix/django-concurrency#86]
The changelog states that release 1.3 drops support for Python < 3.3, but the tests at https://travis-ci.org/saxix/django-concurrency/ still include 2.7 as passing.  Was the changelog intended to mean versions of Python3 <3.3?

Are there any known issues with using release 1.4 on python 2.7?  Thanks!

**Comment by saxix** [comment]
seems the changelog is a bit ambiguous, python 2.7 is actively supported, and v1.4 is used in production with python 2.7 in many projects where I currently work.
