### ISSUE TITLE
Problem with restoring reversion

### ISSUE THREAD

**Issue by davidkrcil** [saxix/django-concurrency#87]
Thanks for nice concurency - It is pretty useful. I have one small problem caused probably by my insufficient knowledge. I am using reversion v2.0.12 with concurrency 1.4 on Django 1.8.18.3
I am getting Record Modified error when I try to restore some older version from history. 
Please could you help?
Thanks David

Here is my admin code:

from reversion.admin import VersionAdmin
from .models import *
from concurrency.admin import ConcurrentModelAdmin
from concurrency.api import disable_concurrency

class OffersAdmin(VersionAdmin, ConcurrentModelAdmin):
    inlines = [
        Accomodation,
        Food,
    ]
    @disable_concurrency()
    def recover_view(self, request, version_id, extra_context=None):
        return super(ReversionConcurrentModelAdmin, self).recover_view(request, version_id, extra_context)

**Comment by saxix** [comment]
@davidkrcil can you extend _"..restore_ some older version.."_ ? It does mean "sometimes" or for "some model" ?
The code seems correct,  but does not looks like your real code, can you double check and sen some other details ?

**Comment by davidkrcil** [comment]
@saxix thanks for reply

I prepared some minimised app in order to learn working with concurrency and because of it the code seems lightweight, but it is fully working.

I am using Django-reversion. And the problem is when I open Order model history. I can open one of older Offer versions. But when I decide to restore it back (when I press button) it brings the Record Modified error 

If I use definition of admin: class OffersAdmin(VersionAdmin, ConcurrentModelAdmin) the error is risen in red block in admin. 

If I use definition of admin: class OffersAdmin(VersionAdmin) it crashes into Django standard yellow error page with details:


Request URL: | http://127.0.0.1:8000/en/admin/ff_offers/offers/2/history/6/
-- | --
1.8.18
RecordModifiedError
Record has been modified
/virtualenv/lib/python3.5/site-packages/concurrency/views.py in callback, line 18
/virtualenv/bin/python
3.5.2

This happen every time when I try to restore some of Offer model history records by pressing "Save button" 

There is my model.py code:

from django.db import models
from django.utils.translation import gettext as _
from ff_catalogue.models_restaurants import *
from ff_catalogue.models_accomodation import *
from concurrency.fields import IntegerVersionField



class Offers(models.Model):
    title = models.CharField(_("Offer title"),max_length=2000, null=True, blank=True)
    # role = models.ForeignKey(photoRoles, verbose_name=_("Photo role"), on_delete=models.CASCADE )

    food = models.ManyToManyField(Food2, through='Offers_has_Food', related_name='offersincategories')

    version = IntegerVersionField()

    class Meta:
        verbose_name = "Offer"
        verbose_name_plural = "Offers"


    def __str__(self):
        return self.title


class Offers_has_Accomodation(models.Model):

    offer = models.ForeignKey(Offers, on_delete=models.CASCADE)
    rooms = models.ForeignKey(hotelPrices, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name = "Room"
        verbose_name_plural = "Rooms"

    def __str__(self):
        return self.rooms.roomSize

class Offers_has_Food(models.Model):

    offer = models.ForeignKey(Offers, on_delete=models.CASCADE)
    menu = models.ForeignKey(Food2, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def cataloguePrice(self):
        if self.menu:
            return self.menu.priceStartsAt
        else:
            return '(Save first)'

    class Meta:
        verbose_name = "Menu"
        verbose_name_plural = "Menus"

    def __str__(self):
        return self.menu.foodName


Here is my complete admin.py:



from django.contrib import admin

from reversion.admin import VersionAdmin
from reversion_compare.admin import CompareVersionAdmin
from .models import *
from concurrency.admin import ConcurrentModelAdmin
from concurrency.api import disable_concurrency

# Register your models here.





class Accomodation(admin.TabularInline):
    model = Offers_has_Accomodation
    extra = 0
    verbose_name = "Acomodation"
    verbose_name_plural = "Acomodation"


class Food(admin.TabularInline):
    model = Offers_has_Food
    extra = 0
    verbose_name = "Food"
    verbose_name_plural = "Food"
    fields = ("menu","price","cataloguePrice",)
    readonly_fields = ('cataloguePrice',)


class OffersAdmin(VersionAdmin, ConcurrentModelAdmin):
    inlines = [
        Accomodation,
        Food,
    ]
    @disable_concurrency()
    def recover_view(self, request, version_id, extra_context=None):
        return super(ReversionConcurrentModelAdmin, self).recover_view(request, version_id, extra_context)


admin.site.register(Offers, OffersAdmin)

**Comment by claytondaley** [comment]
Have you tried to [`disable_concurrence`](https://django-concurrency.readthedocs.io/en/latest/api.html#disable-concurrency)?  This sounds like a prototypical concurrency error:

You're trying to replace a version number X with a version number Y.  In optimistic concurrency, we assume that Y is a previous version and reject the change.  If you want to allow the change, you need to disable the checking.

**Comment by saxix** [comment]
@davidkrcil what sounds strange, is this part of the code
```@disable_concurrency()
def recover_view(self, request, version_id, extra_context=None):
       return super(ReversionConcurrentModelAdmin, self).recover_view(request, version_id, extra_context)
```
`ReversionConcurrentModelAdmin` is not your model and either is not imported, so seems that `recover_view` is not called and `disable_concurrency` has no effect. You should check what view is invoked when you "press the button" and apply `disable_concurrency` there.

**Comment by davidkrcil** [comment]
@saxix I changed model admin parameters mistake but with no effect

I am trying both documented variants of disabling concurrency (one you can see commented) but it seems that this method is not fired in my code - I added print("render_revision_form fired") to ensure that it runs in this lines of code, but I can't fid "render_revision_form fired" in terminal 

Please would you have some other hint how to resolve?

THX
 
class OffersAdmin(VersionAdmin, ConcurrentModelAdmin):
    inlines = [
        Accomodation,
        Food,
    ]
    @disable_concurrency()
    def recover_view(self, request, version_id, extra_context=None):
        print("render_revision_form fired")
        return super(OffersAdmin, self).recover_view(request, version_id, extra_context)

    # def render_revision_form(self, request, obj, version, context, revert=False, recover=False):
    #     print("render_revision_form fired")
    #     with disable_concurrency(obj):
    #         return super(OffersAdmin, self).render_revision_form(request, obj, version, context, revert, recover)

admin.site.register(Offers, OffersAdmin)

**Comment by saxix** [comment]
@davidkrcil I'm not a django-reversion expert, you should check which ModelAdmin method is invoked when you "press the button". If you cannot get it from the django-reversion documentation, try this procedure:
 - add `print(<method_name>` to any view of `VersionAdmin` that accept request as first parameter (or check the `get_urls` method to detect all the views
- run the app and "press the button" until you do not understand what is the involved view
- override that view in your   `OffersAdmin` and decorate it with `@disable_concurrency`

hope this helps.

**Comment by saxix** [comment]
@davidkrcil any updates on this issue ?

**Comment by blueyed** [comment]
I've found this: https://django-concurrency.readthedocs.io/en/latest/cookbook.html#recover-deleted-record-with-django-reversion, where the second methods works with django-revision 3.0.0.
