### ISSUE TITLE
Question: is Django 2.0 fully supported?

### ISSUE THREAD

**Issue by QinMing** [saxix/django-concurrency#92]
Hi Stefano,

I see a commit ( https://github.com/saxix/django-concurrency/commit/a1bcf1773d2a4923720c1aa8deb57570fc476b0a ) that added support for Django 2. But on the readme, it still says

> Supported Django versions: 1.8.x, 1.9.x, 1.10.x., 1.11.x

I'm wondering if it's safe to start my new project with Django 2

Thank you!

**Comment by saxix** [comment]
yep, it is a  readme error, I'm using it with django 2.0.3 just now
